-- 1
ALTER TABLE reviews
ADD CONSTRAINT prod_code
FOREIGN KEY (productcode) REFERENCES productlist (productcode)

ALTER TABLE orders
ADD CONSTRAINT prod_code_ord
FOREIGN KEY (productcode) REFERENCES productlist (productcode)

ALTER TABLE userlibrary
ADD CONSTRAINT user_id
FOREIGN KEY (userid) REFERENCES userbase (userid)

-- 2

SELECT 
    FIRSTNAME || ' ' || LASTNAME AS FULL_NAME,
    USERNAME
FROM USERBASE
WHERE FLOOR(MONTHS_BETWEEN(SYSDATE, BIRTHDAY) / 12) >= 18;

-- 3

SELECT 
    MAX(LENGTH(USERNAME)) AS MAX_USERNAME_LENGTH,
    ROUND(AVG(LENGTH(USERNAME)), 2) AS AVG_USERNAME_LENGTH
FROM USERBASE;

-- 4

SELECT QUESTION
FROM SECURITYQUESTION
WHERE LOWER(QUESTION) LIKE 'what is%'
   OR LOWER(QUESTION) LIKE 'what was%';

-- 5

SELECT 
    PRODUCTCODE,
    MIN(RATING) AS LOWEST_RATING,
    MAX(RATING) AS HIGHEST_RATING,
    TRUNC(AVG(RATING)) AS AVG_RATING,
    COUNT(*) AS REVIEW_COUNT
FROM REVIEWS
GROUP BY PRODUCTCODE
ORDER BY REVIEW_COUNT DESC;

-- 6

SELECT 
    PRODUCTCODE,
    COUNT(*) AS USER_COUNT
FROM WISHLIST
WHERE POSITION = 1
GROUP BY PRODUCTCODE;


-- 7

SELECT 
    USERID,
    SUM(PRICE) AS TOTAL_SPENT
FROM ORDERS
GROUP BY USERID;

-- 8

SELECT 
    PURCHASEDATE,
    SUM(PRICE) AS GROSS_PROFIT
FROM ORDERS
GROUP BY PURCHASEDATE
ORDER BY GROSS_PROFIT DESC;

-- 9

SELECT 
    PRODUCTCODE,
    SUM(HOURSPLAYED) AS TOTAL_HOURS_PLAYED
FROM USERLIBRARY
GROUP BY PRODUCTCODE
ORDER BY TOTAL_HOURS_PLAYED DESC
FETCH FIRST 5 ROWS ONLY;

-- 10

CREATE OR REPLACE VIEW USER_INFRACTION_COUNTS AS
SELECT 
    USERID,
    COUNT(*) AS INFRACTION_COUNT
FROM INFRACTIONS
GROUP BY USERID
ORDER BY COUNT(*) DESC;

SELECT * FROM USER_INFRACTION_COUNTS

-- 11

CREATE OR REPLACE VIEW USER_RULE_INFRACTION_COUNTS AS
SELECT 
    USERID,
    RULENUM,
    COUNT(*) AS INFRACTION_COUNT
FROM INFRACTIONS
GROUP BY USERID, RULENUM;

SELECT * FROM USER_RULE_INFRACTION_COUNTS

-- 12

SELECT 
    RULENUM,
    PENALTY,
    COUNT(*) AS PENALTY_COUNT
FROM INFRACTIONS
GROUP BY RULENUM, PENALTY;

-- 13

SELECT 
    AVG(DATEUPDATED - DATESUBMITTED) AS AVG_TURNAROUND_DAYS,
    MAX(DATEUPDATED - DATESUBMITTED) AS MAX_TURNAROUND_DAYS,
    MIN(DATEUPDATED - DATESUBMITTED) AS MIN_TURNAROUND_DAYS
FROM USERSUPPORT
WHERE STATUS = 'CLOSED';

-- 14

SELECT 
    EMAIL,
    ISSUE,
    DATESUBMITTED,
    COUNT(*) AS ISSUE_COUNT
FROM USERSUPPORT
WHERE STATUS = 'NEW'
GROUP BY EMAIL, ISSUE, DATESUBMITTED
ORDER BY ISSUE_COUNT DESC;

-- 15

SELECT 
    USERID,
    FIRSTNAME,
    LASTNAME,
    USERNAME
FROM USERBASE
WHERE PASSWORD LIKE '%' || FIRSTNAME || '%'
   OR PASSWORD LIKE '%' || LASTNAME || '%';

-- 16

SELECT 
    PUBLISHER,
    AVG(PRICE) AS AVG_PRICE
FROM PRODUCTLIST
GROUP BY PUBLISHER
ORDER BY PUBLISHER ASC;

-- 17

CREATE OR REPLACE VIEW OLD_PRODUCT_DISCOUNTS AS
SELECT 
    PRODUCTNAME,
    PRICE * 0.75 AS DISCOUNTED_PRICE
FROM PRODUCTLIST
WHERE RELEASEDATE < ADD_MONTHS(SYSDATE, -60);

SELECT * FROM OLD_PRODUCT_DISCOUNTS

-- 18

SELECT 
    GENRE,
    MAX(PRICE) AS MAX_PRICE,
    MIN(PRICE) AS MIN_PRICE
FROM PRODUCTLIST
GROUP BY GENRE;

-- 19

CREATE OR REPLACE VIEW RECENT_CHATLOG AS
SELECT *
FROM CHATLOG
WHERE DATESENT BETWEEN (SYSDATE - 7) AND SYSDATE;

SELECT * FROM RECENT_CHATLOG

-- 20

CREATE OR REPLACE VIEW RECENT_PENALTIES AS
SELECT 
    USERID,
    DATEASSIGNED,
    PENALTY
FROM INFRACTIONS
WHERE PENALTY IS NOT NULL
  AND DATEASSIGNED >= ADD_MONTHS(SYSDATE, -1);

SELECT * FROM RECENT_PENALTIES